name: Run Stock Analysis Script

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码仓库
      uses: actions/checkout@v3

    - name: 设置 Python 版本
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: 升级 pip
      run: pip install --upgrade pip

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: 安装依赖项
      run: |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          pip install akshare pandas
          # 根据需要添加其他依赖项
        fi

    - name: 运行 Python 脚本
      run: python 相似K线计算代码.py
